# Daily cleanup of readmarks.
clean_up_readmarks_job:
  cron: "0 3 * * *"
  class: "CleanUpReadMarksJob"
  queue: "lowest"

# Run the ConsolidatedItemEmailJob for opening reminders on the 5th minute of each hour.
consolidated_item_email_job:
  cron: "5 * * * *"
  class: "ConsolidatedItemEmailJob"
  queue: "default"
